"""CR-7 R1 research-ready security daily panel.

R1 consumes only a verified CR-4 ReadModel snapshot.  It publishes an
immutable, versioned Parquet panel with an explicit semantic manifest.  The
index panel remains disabled until the repository has a verified index
identity/read-model contract.
"""

from ashare_state.research.eligibility import EligibilityDecision, evaluate_daily_bar
from ashare_state.research.historical import (
    COMPLETE_OBSERVED_DAILY_BAR_SCOPE,
    PARTIAL_OBSERVED_DAILY_BAR_SCOPE,
    CoverageBasisDescriptor,
    CoverageBasisError,
    CoverageEvaluation,
    HistoricalArtifact,
    HistoricalMaterializationError,
    HistoricalMaterializationPlan,
    HistoricalMaterializationReader,
    HistoricalReadError,
    MaterializationConflictError,
    MaterializationResult,
    OfflineHistoricalMaterializer,
    PartitionKey,
    WriterRuntimeLock,
    build_fixture_coverage_basis_descriptor,
    build_materialization_identity,
    build_writer_runtime_lock_identity,
    compute_coverage_basis_set_hash,
    compute_dependency_lock_content_hash,
    compute_idempotency_key,
    compute_materialization_id,
    compute_writer_runtime_lock_hash,
    expected_partition_keys,
    verify_coverage_basis,
)
from ashare_state.research.models import (
    BSE_IDENTITY_BOUNDARY_STATE,
    INDEX_PANEL_STATE,
    PRICE_BASIS,
    RESEARCH_CONTRACT_VERSION,
    RESEARCH_DATASET_VERSION,
    RESEARCH_SECURITY_DAILY_DATASET,
    RESEARCH_SECURITY_DAILY_FIELDS,
    RESEARCH_SECURITY_DAILY_FIXTURE_DATASET,
    RESEARCH_SECURITY_DAILY_SCHEMA_VERSION,
    UNIVERSE_BASIS,
    CoverageState,
    DataQualityState,
    ExclusionReason,
    IdentityRecord,
    IdentitySource,
    IdentityView,
    IndexPanelState,
    ResearchEligibility,
    ResearchManifest,
    ResearchManifestError,
    ResearchPanelError,
    ResearchReaderError,
    ResearchSplit,
    research_security_daily_schema,
)
from ashare_state.research.panel import (
    ResearchBuildResult,
    ResearchPanelBuilder,
    VerifiedResearchProjection,
)
from ashare_state.research.reader import (
    ResearchPanelReader,
    load_disabled_research_security_daily,
    load_research_security_daily,
)
from ashare_state.research.splits import (
    assert_research_split_date,
    assign_research_split,
    split_window,
)

__all__ = [
    "BSE_IDENTITY_BOUNDARY_STATE",
    "COMPLETE_OBSERVED_DAILY_BAR_SCOPE",
    "CoverageState",
    "CoverageBasisDescriptor",
    "CoverageBasisError",
    "CoverageEvaluation",
    "DataQualityState",
    "EligibilityDecision",
    "ExclusionReason",
    "HistoricalArtifact",
    "HistoricalMaterializationError",
    "HistoricalMaterializationPlan",
    "HistoricalMaterializationReader",
    "HistoricalReadError",
    "INDEX_PANEL_STATE",
    "IdentityRecord",
    "IdentitySource",
    "IdentityView",
    "IndexPanelState",
    "PRICE_BASIS",
    "PartitionKey",
    "RESEARCH_CONTRACT_VERSION",
    "RESEARCH_DATASET_VERSION",
    "RESEARCH_SECURITY_DAILY_DATASET",
    "RESEARCH_SECURITY_DAILY_FIXTURE_DATASET",
    "RESEARCH_SECURITY_DAILY_FIELDS",
    "RESEARCH_SECURITY_DAILY_SCHEMA_VERSION",
    "ResearchBuildResult",
    "VerifiedResearchProjection",
    "ResearchEligibility",
    "ResearchManifest",
    "ResearchManifestError",
    "ResearchPanelBuilder",
    "ResearchPanelError",
    "ResearchPanelReader",
    "ResearchReaderError",
    "ResearchSplit",
    "MaterializationConflictError",
    "MaterializationResult",
    "OfflineHistoricalMaterializer",
    "PARTIAL_OBSERVED_DAILY_BAR_SCOPE",
    "UNIVERSE_BASIS",
    "WriterRuntimeLock",
    "assign_research_split",
    "assert_research_split_date",
    "evaluate_daily_bar",
    "build_fixture_coverage_basis_descriptor",
    "build_materialization_identity",
    "build_writer_runtime_lock_identity",
    "compute_coverage_basis_set_hash",
    "compute_dependency_lock_content_hash",
    "compute_idempotency_key",
    "compute_materialization_id",
    "compute_writer_runtime_lock_hash",
    "expected_partition_keys",
    "load_disabled_research_security_daily",
    "load_research_security_daily",
    "research_security_daily_schema",
    "split_window",
    "verify_coverage_basis",
]
